import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import 'report_service.dart';

/// Builds the Cardiac Risk Report as a proper paginated PDF document —
/// mirrors fromDaria/generate_report_html.py's HTML report content exactly
/// (see report_screen.dart, which mirrors the same content on-screen), but
/// as a real multi-page PDF rather than a screenshot, so the OS print/
/// save-as-PDF flow actually works instead of cropping a single tall image
/// to one page.
class PdfReportService {
  PdfReportService._();

  static final _bg = PdfColor.fromHex('#FAF8F5');
  static final _card = PdfColors.white;
  static final _green = PdfColor.fromHex('#7CB686');
  static final _textPrimary = PdfColor.fromHex('#2D3142');
  static final _textSecondary = PdfColor.fromHex('#6B7280');
  static final _warning = PdfColor.fromHex('#F59E0B');
  static final _error = PdfColor.fromHex('#EF5350');
  static final _warningBg = PdfColor.fromHex('#FFF8E3');
  static final _border = PdfColor.fromHex('#EEEEEE');

  /// The PDF's default font (Helvetica, a base-14 PDF font) only covers
  /// WinAnsi/Latin-1 — it has no glyph for an em dash (U+2014), which shows
  /// up both in this file's own strings and in report_service.dart's
  /// kFeatureInfo descriptions (e.g. "LF Power"). Substituting a plain
  /// hyphen is simpler and more robust than bundling a Unicode font just
  /// for one character.
  static String _safe(String text) => text.replaceAll('—', '-');

  static PdfColor _riskColor(String level) {
    switch (level) {
      case 'LOW':
        return _green;
      case 'MEDIUM':
        return _warning;
      default:
        return _error;
    }
  }

  static String _formatDate(DateTime dt) {
    const months = [
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
    ];
    final h = dt.hour % 12 == 0 ? 12 : dt.hour % 12;
    final m = dt.minute.toString().padLeft(2, '0');
    final ampm = dt.hour < 12 ? 'AM' : 'PM';
    return '${months[dt.month - 1]} ${dt.day}, ${dt.year} · $h:$m $ampm';
  }

  static Future<Uint8List> build(FinalReport report, List<FeatureRow> topFeatures) async {
    final doc = pw.Document();
    final color = _riskColor(report.riskLevel);
    final pct = report.score * 100;

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          pw.Text(
            'Heart Sclerosis Risk Report',
            style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold, color: _textPrimary),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            'AI Bracelet System  ·  NUST Politehnica Bucharest  ·  ${_formatDate(report.computedAt)}',
            style: pw.TextStyle(fontSize: 10, color: _textSecondary),
          ),
          pw.SizedBox(height: 16),
          _disclaimer(),
          pw.SizedBox(height: 16),
          _scoreSection(color, pct, report),
          pw.SizedBox(height: 16),
          _sectionTitle('Session Overview'),
          pw.SizedBox(height: 10),
          _overviewGrid(report),
          pw.SizedBox(height: 16),
          _sectionTitle('Top Influential Features'),
          pw.SizedBox(height: 10),
          _featuresTable(topFeatures),
          pw.SizedBox(height: 20),
          pw.Divider(color: _border),
          pw.SizedBox(height: 8),
          pw.Text(
            'Generated by AI Bracelet for Early Detection of Heart Sclerosis  ·  '
            'Model: XGBoost (AUC 0.986, Accuracy 93.7%)  ·  '
            'Daria Gladkykh · FatemehSadat MahmoudzadehHosseini · Prof. Dr. Ing. Nicolae Goga',
            style: pw.TextStyle(fontSize: 8, color: _textSecondary),
            textAlign: pw.TextAlign.center,
          ),
        ],
      ),
    );

    return doc.save();
  }

  static pw.Widget _disclaimer() {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: _warningBg,
        border: pw.Border.all(color: _warning, width: 0.8),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Text(
        _safe(
          'This is a research prototype, not a medical device. This report is designed to '
          'support — not replace — clinical evaluation. A score above 30% should prompt a '
          'cardiologist referral. All analysis runs locally on your device. No data is sent anywhere.',
        ),
        style: pw.TextStyle(fontSize: 9.5, color: _textPrimary, lineSpacing: 2),
      ),
    );
  }

  static pw.Widget _scoreSection(PdfColor color, double pct, FinalReport report) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.symmetric(vertical: 20, horizontal: 20),
      decoration: pw.BoxDecoration(
        color: _card,
        borderRadius: pw.BorderRadius.circular(12),
        border: pw.Border.all(color: _border),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        children: [
          pw.Text(
            '${pct.toStringAsFixed(1)}%',
            style: pw.TextStyle(fontSize: 40, fontWeight: pw.FontWeight.bold, color: color),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            'CARDIAC RISK SCORE',
            style: pw.TextStyle(fontSize: 10, color: _textSecondary, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 8),
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(horizontal: 14, vertical: 5),
            decoration: pw.BoxDecoration(color: color, borderRadius: pw.BorderRadius.circular(14)),
            child: pw.Text(
              '${report.riskLevel} RISK',
              style: pw.TextStyle(fontSize: 10, color: PdfColors.white, fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.SizedBox(height: 14),
          pw.ClipRRect(
            horizontalRadius: 4,
            verticalRadius: 4,
            child: pw.LinearProgressIndicator(
              value: report.score.clamp(0.0, 1.0),
              minHeight: 8,
              backgroundColor: PdfColor.fromHex('#EFEFEF'),
              valueColor: color,
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('0% - Healthy', style: pw.TextStyle(fontSize: 8, color: _textSecondary)),
              pw.Text('50%', style: pw.TextStyle(fontSize: 8, color: _textSecondary)),
              pw.Text('100% - High Risk', style: pw.TextStyle(fontSize: 8, color: _textSecondary)),
            ],
          ),
          pw.SizedBox(height: 14),
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              color: _bg,
              border: pw.Border(left: pw.BorderSide(color: color, width: 3)),
            ),
            child: pw.Text(
              _safe(report.assessment),
              style: pw.TextStyle(fontSize: 10, color: _textPrimary, lineSpacing: 2),
              textAlign: pw.TextAlign.left,
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _sectionTitle(String title) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.only(bottom: 6),
      decoration: pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: _green, width: 1.2)),
      ),
      child: pw.Text(
        title,
        style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold, color: _textPrimary),
      ),
    );
  }

  static pw.Widget _overviewGrid(FinalReport report) {
    // Mirrors fromDaria's meta-grid exactly except "File" — no single
    // source filename applies in the live app (a session is assembled from
    // many synced pw*.csv chunks) — see report_screen.dart's identical note.
    final items = [
      ['Windows analysed', '${report.nWindows}'],
      ['Data rows', '${report.nRows}'],
      ['Session duration', '~${report.durationHours.toStringAsFixed(1)} hours'],
      ['Mean HR', '${report.meanHr.toStringAsFixed(0)} bpm'],
      ['Mean RMSSD', '${report.meanRmssd.toStringAsFixed(1)} ms'],
      ['Generated', _formatDate(report.computedAt)],
    ];

    pw.Widget cell(List<String> item) => pw.Container(
          padding: const pw.EdgeInsets.all(8),
          decoration: pw.BoxDecoration(color: _bg, borderRadius: pw.BorderRadius.circular(6)),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(item[0].toUpperCase(), style: pw.TextStyle(fontSize: 7.5, color: _textSecondary)),
              pw.SizedBox(height: 2),
              pw.Text(item[1], style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: _textPrimary)),
            ],
          ),
        );

    final rows = <pw.Widget>[];
    for (var i = 0; i < items.length; i += 2) {
      final second = i + 1 < items.length ? items[i + 1] : null;
      rows.add(
        pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 8),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(child: cell(items[i])),
              pw.SizedBox(width: 8),
              pw.Expanded(child: second != null ? cell(second) : pw.SizedBox()),
            ],
          ),
        ),
      );
    }
    return pw.Column(children: rows);
  }

  static pw.Widget _featuresTable(List<FeatureRow> features) {
    final maxImportance = features.map((f) => f.importance).fold(0.0, (a, b) => a > b ? a : b);

    return pw.Table(
      columnWidths: {
        0: const pw.FixedColumnWidth(18),
        1: const pw.FlexColumnWidth(2.3),
        2: const pw.FlexColumnWidth(1.4),
        3: const pw.FlexColumnWidth(1.8),
        4: const pw.FlexColumnWidth(3.4),
      },
      children: [
        pw.TableRow(
          decoration: pw.BoxDecoration(color: _textPrimary),
          children: [
            _th('#'),
            _th('Feature'),
            _th('Value'),
            _th('Importance'),
            _th('Clinical meaning'),
          ],
        ),
        ...features.asMap().entries.map((entry) {
          final i = entry.key + 1;
          final f = entry.value;
          final barWidth = maxImportance > 0 ? (f.importance / maxImportance) : 0.0;
          final isEven = entry.key % 2 == 1;
          final rowColor = isEven ? _bg : PdfColors.white;
          return pw.TableRow(
            decoration: pw.BoxDecoration(color: rowColor),
            children: [
              _td('$i', rowColor),
              _td(_safe(f.label), rowColor, bold: true),
              _td(
                f.unit.isEmpty ? f.value.toStringAsFixed(3) : '${f.value.toStringAsFixed(3)} ${f.unit}',
                rowColor,
              ),
              pw.Container(
                padding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 5),
                child: pw.ClipRRect(
                  horizontalRadius: 3,
                  verticalRadius: 3,
                  child: pw.LinearProgressIndicator(
                    value: barWidth,
                    minHeight: 6,
                    backgroundColor: PdfColor.fromHex('#EFEFEF'),
                    valueColor: _green,
                  ),
                ),
              ),
              _td(_safe(f.description), rowColor, fontSize: 8, color: _textSecondary),
            ],
          );
        }),
      ],
    );
  }

  static pw.Widget _th(String text) => pw.Padding(
        padding: const pw.EdgeInsets.all(6),
        child: pw.Text(
          text,
          style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: PdfColors.white),
        ),
      );

  static pw.Widget _td(
    String text,
    PdfColor bg, {
    bool bold = false,
    double fontSize = 9,
    PdfColor? color,
  }) =>
      pw.Padding(
        padding: const pw.EdgeInsets.all(6),
        child: pw.Text(
          text,
          style: pw.TextStyle(
            fontSize: fontSize,
            fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
            color: color ?? _textPrimary,
          ),
        ),
      );
}
